version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: lolcopter
        databases:
          default:
            connector: postgres
            host: postgres
            database: habbit
            user: prisma
            password: prisma
            rawAccess: true
            port: '5432'
            migrations: true
  postgres:
    image: postgres:10.5
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
